- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true

- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Swap file permissions
  ansible.builtin.file:
    path: "{{ swap_file }}"
    mode: "0600"
  listen: Format and enable swap

- name: Format swap
  ansible.builtin.command: mkswap {{ swap_file }}
  changed_when: true
  listen: Format and enable swap

- name: Enable swap
  ansible.builtin.command: swapon {{ swap_file }}
  changed_when: true
  listen: Format and enable swap
